### ISSUE TITLE
I find the signature don't work and the request json do not store as dirct. 

### ISSUE THREAD

**Issue by thinksource** [davidfischer/rpc4django#27]
hi,

I just applying javascript to send an json string and find the received part have some issues:

this is my javascript:

    function clickhere(){
		data='{"jsonrpc": "2.0", "method": "secret", "params": {"a": "as12"}, "id": 1}'
		$.post(
				'RPC2',
		         data,
		         function(data1) {
		           alert("Response: " + data1);
		         }
		         );

this is my received part:

    @csrf_exempt
    @rpcmethod(name='secret', signature=['string', 'string'])
    def add(request, mystr):
  
         print request.COOKIES
         print request.body
         re=request.REQUEST
         print repr(re)

        for k in re:
             print "dict[%s] =" % k,re[k]
        rep = re.get('params', None)
        print rep
        return HttpResponse(json.dumps('tytr'), content_type="application/json")

the first problem(error) is:

Internal Server Error: /RPC2
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\core\handlers\base.py", line 115, i
n get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "C:\Python27\lib\site-packages\django\views\decorators\csrf.py", line 77,
 in wrapped_view
    return view_func(*args, **kwargs)
TypeError: add() takes exactly 2 arguments (1 given)
[09/Jul/2013 11:18:02] "POST /RPC2 HTTP/1.1" 500 10604

when I change the  def add(request, mystr)=> def add(request)  and then there is no error.

second problem:
when I print I simply get the:
   dict[{"jsonrpc": "2.0", "method": "secret", "params": {"a": "as12"}, "id": 1}] =
I mean I simply get the json-rpc string, but not params and methods.

**Comment by angvp** [comment]
Not a bug, close it
