### ISSUE TITLE
JSON-RPC 2.0 Specification, 'error' set to 'None' in correct response

### ISSUE THREAD

**Issue by rtp-calpoly** [davidfischer/rpc4django#32]
In accordance with JSON-RPC 2.0 specification (http://www.jsonrpc.org/specification#response_object), the response object must not contain an 'error' field in case of a correct method execution. Current 0.25 implementation includes an 'error' field in the response set to 'None' after a correct method invokation (method "jsonrpcdispatcher._encode_result"), which makes certain client implementations to fail.

For correcting this issue, it is only necessary to erase line #57 on file 'jsonrpcdispatcher.py':

    def _encode_result(self, jsonid, result, error):
        res = {'jsonrpc': '2.0', 'id': jsonid}

        if error is None:
            # res['error'] = None     ### invocation correct -> no error field
            res['result'] = result
        else:
            res['error'] = error
            res['error']['name'] = 'JSONRPCError'
            res['result'] = None

**Comment by xcrespo** [comment]
The same must be done with the last line. When an error is produced, the field 'result' must not be sent.

```python
def _encode_result(self, jsonid, result, error):
    res = {'jsonrpc': '2.0', 'id': jsonid}

    if error is None:
        # res['error'] = None     ### invocation correct -> no error field
        res['result'] = result
    else:
        res['error'] = error
        res['error']['name'] = 'JSONRPCError'
        # res['result'] = None    ### invocation failure/exception -> no result field
```

**Comment by davidfischer** [comment]
With the fix merged, I believe this is fixed.
